(() => {
'use strict';
const root = document.getElementById('pair-analysis');
const el = id => document.getElementById(id);
const text = (tag, value, parent) => { const n=document.createElement(tag); n.textContent=value; if(parent)parent.appendChild(n); return n; };
const val = (o, keys) => { for(const k of keys) if(o && o[k] !== undefined && o[k] !== null) return o[k]; return null; };
const fmt = x => x === null || x === undefined ? 'Unavailable' : typeof x === 'number' ? (Number.isInteger(x)?String(x):x.toFixed(4)) : String(x);
const table = (headers, rows, parent) => {const wrap=text('div','',parent);wrap.className='pair-scroll';const t=text('table','',wrap);const head=text('tr','',text('thead','',t));headers.forEach(h=>text('th',h,head));const body=text('tbody','',t);rows.forEach(r=>{const tr=text('tr','',body);r.forEach(v=>text('td',fmt(v),tr));});return t;};
const status = p => p.status || p.eligibility_status || 'uncomputed';
fetch('pair-analysis-staged/data.json').then(r=>{if(!r.ok)throw Error('Registry fetch '+r.status);return r.json();}).then(d=>{
 text('span',`Cohort ${d.cohort_version} · ${d.groups.length} groups · ${d.pairs.length} registered pairs · ${d.results.filter(r=>r.status==='completed').length} completed result arms; reference coverage ${d.pairs.filter(p=>['original','pca75'].every(a=>d.results.some(r=>r.pair_id===p.pair_id&&r.arm===a&&r.status==='completed'))).length}/${d.pairs.length} registered pairs (held and pending pairs remain in denominator).`,el('pair-summary')); el('pair-summary').firstChild.remove();
 const source=d.source_summary||{};if(source.relationships)text('p',source.relationships,el('pair-source-summary'));if(source.all_new_fits_stopped){const warning=text('p','Execution stopped: '+(source.reason||'source integrity review required')+'. Completed verified results remain visible; uncomputed results are unavailable, not zero.',el('pair-source-summary'));warning.className='pair-warning';}if(source.approved_source_exception){text('p','Approved source exception: '+(typeof source.approved_source_exception==='string'?source.approved_source_exception:JSON.stringify(source.approved_source_exception)),el('pair-source-summary'));}if(source.source_birds!==undefined)text('p',`Source inventory: ${source.source_birds} birds; ${fmt(source.header_timing_retained_observations)} header/timing-retained intervals; ${fmt(source.unreviewed_below_5ms)} unreviewed intervals below 5 ms. These counts do not establish QC-certified complete syllables or completed pair coverage.`,el('pair-source-summary'));
 const groupSelect=el('pair-group'), pairSelect=el('pair-select');
 d.groups.forEach(g=>{const ps=d.pairs.filter(p=>p.group_id===g.group_id);const pid=new Set(ps.map(p=>p.pair_id));const counts={};ps.forEach(p=>{const s=status(p);counts[s]=(counts[s]||0)+1;});const tr=text('tr','',el('pair-coverage'));[g.group_id+' / '+(g.tutor_id||'not recorded'),g.evidence_tier||g.relationship_evidence_tier||'See pair evidence',String(ps.length)+(g.candidate_pupils?' catalogued; '+g.candidate_pupils.length+' candidate pupils':''),d.results.filter(r=>pid.has(r.pair_id)&&r.status==='completed').length,Object.entries(counts).map(([k,v])=>`${k}: ${v}`).join('; ')||'No mapped pairs'].forEach(v=>text('td',String(v),tr));const o=text('option',g.group_id,groupSelect);o.value=g.group_id;});
 const endpoint = (r,bird,role) => {const m=r.metrics||{};if(m.endpoints&&m.endpoints[role])return m.endpoints[role];const by=r.per_bird||m.per_bird||r.bird_metrics; if(Array.isArray(by))return by.find(x=>x.bird===bird||x.bird_id===bird)||{};return m[role]||r[role]||(by&&by[bird])||{};};
 const hvalue=(m,assigned)=>m[assigned?'assigned_only':'noise_included'] ? val(m[assigned?'assigned_only':'noise_included'],['H_bits','entropy_bits']) : val(m,assigned?['entropy_assigned_bits','assigned_only_entropy_bits','entropy_clustered_bits','H_assigned','h_assigned']:['entropy_noise_inclusive_bits','entropy_including_noise_bits','entropy_all_bits','H_inclusive','h_inclusive']);
 const show = () => {const p=d.pairs.find(p=>p.pair_id===pairSelect.value);const box=el('pair-detail');box.replaceChildren();if(!p){text('p','No mapped pair in this group.',box);return;}text('h3',`${p.tutor_id||'Unknown tutor'} → ${p.pupil_id||'Unknown pupil'}`,box);text('p',`Evidence: ${p.evidence_tier||p.relationship_evidence_tier||'unspecified'}. Status: ${status(p)}. ${p.reason||p.status_reason||''}`,box);
 const arms=d.results.filter(r=>r.pair_id===p.pair_id);const tasks=d.tasks.filter(t=>t.pair_id===p.pair_id);
 if(!arms.length)text('p','Results are unavailable / uncomputed. Missing results are not zero.',box);
 if(p.agreement&&['original','pca75'].every(a=>arms.some(r=>r.arm===a&&r.status==='completed')))text('p','Original / PCA75 matched-observation partition agreement: '+JSON.stringify(p.agreement),box);
 arms.forEach(r=>{text('h4',`${r.arm||r.representation||'Analysis arm'} · ${r.status||'status not recorded'}`,box);if(r.status!=='completed'){text('p',r.reason||r.error||'Result not complete.',box);return;}
 const config=r.config||{};const support=r.support||r.representation_support||config.support||config.representation_support||{};const representation=support.representation||support;const supportSummary={shape:support.shape,frames:representation.n_time_frames,padded_samples:representation.cutoff_samples};const dims=val(r,['analysis_dimensions','n_components','dimensions'])??val(config,['analysis_dimensions','n_components','dimensions']);text('p',`Backend: ${fmt(r.backend||config.backend)}. Analysis dimensions: ${fmt(dims)}. Settings: ${JSON.stringify(r.settings||config.setting||{})}. Pair support: ${JSON.stringify(supportSummary)}.`,box);
 if(config.pca_transform){const pc=config.pca_transform; text('p',`Joint unwhitened PCA: threshold ${pc.selected_threshold_percent}%; actual retained variance ${fmt(pc.selected_threshold?.retained_variance)}; components ${fmt(pc.selected_threshold?.components)}; theoretical rank limit ${fmt(pc.theoretical_rank_limit)}. Solver: ${pc.solver}. Precision: ${pc.precision}. Centering: ${pc.centering}.`,box);}
 const rows=['tutor','pupil'].map(role=>{const bird=p[role+'_id'];const m=endpoint(r,bird,role);const n=val(m,['n_total','n_observations','n','observations','count']);const assigned=val(m.assigned_only,['denominator'])??val(m,['n_assigned','assigned_count','assigned']);const ha=hvalue(m,false), hc=hvalue(m,true);return [role+' '+bird,n,val(m,['n_recordings','recording_count','recordings']),val(m,['n_dates','date_count','dates']),val(m,['noise_fraction','noise_rate']),assigned,ha,ha===null?null:2**ha,hc,hc===null?null:2**hc];});
 table(['Bird','Observations / inclusive denominator','Recordings','Dates','Noise fraction','Assigned denominator','H incl. noise (bits)','Effective categories incl.','H assigned (bits)','Effective categories assigned'],rows,box);
 table(['Bird','Occupied categories incl. noise','Evenness incl. noise','Occupied assigned categories','Evenness assigned','Duration min / median / max (s)'],['tutor','pupil'].map(role=>{const m=endpoint(r,p[role+'_id'],role),dur=m.duration_summary||{};return [role,val(m.noise_included,['occupied_category_count']),val(m.noise_included,['evenness']),val(m.assigned_only,['occupied_category_count']),val(m.assigned_only,['evenness']),[dur.minimum,dur.median,dur.maximum].map(fmt).join(' / ')];}),box);
 const tutor=endpoint(r,p.tutor_id,'tutor'),pupil=endpoint(r,p.pupil_id,'pupil');const diff=a=>{const t=hvalue(tutor,a),u=hvalue(pupil,a);return t===null||u===null?null:u-t;};table(['Pupil − tutor, inclusive bits','Pupil − tutor, assigned bits'],[[diff(false),diff(true)]],box);
 if(r.duration||r.duration_summary)text('p','Duration diagnostics: '+JSON.stringify(r.duration||r.duration_summary),box);
 if(r.agreement)text('p','Partition agreement and common-assigned coverage: '+JSON.stringify(r.agreement),box);
 if(r.sampling_diagnostics)text('p','Conditional fixed-partition sampling diagnostics: '+JSON.stringify(r.sampling_diagnostics),box);
 const details=text('details','',box);text('summary','Safe configuration, counts, occupancy and provenance',details);text('pre',JSON.stringify(r,null,2),details);
 });
 text('h4','Task and secondary-method status',box);table(['Task / method','Status','Reason'],tasks.map(t=>[t.arm||t.representation||t.task_id||t.id,t.status||'pending',t.reason||t.error||'']).concat(['pca70','pca85','density sensitivities','UMAP 10D · Euclidean','UMAP 10D · cosine','PCoA','t-SNE','PHATE'].filter(method=>!tasks.some(t=>(t.arm||t.representation)===method)&&!arms.some(r=>r.arm===method)).map(method=>[method,'uncomputed / pending','No completed artifact supplied; analysis/display capability requires method-specific validation.'])),box);text('p','PCoA, UMAP, t-SNE and PHATE are not implied complete by interface availability. No embedding plot is shown without actual coordinates.',box);
 const provenance=text('details','',box);text('summary','Pair evidence, cohort and inclusion record',provenance);text('pre',JSON.stringify(p,null,2),provenance);
 };
 const selectGroup=()=>{pairSelect.replaceChildren();d.pairs.filter(p=>p.group_id===groupSelect.value).forEach(p=>{const o=text('option',`${p.tutor_id||'?'} → ${p.pupil_id||'?'} · ${status(p)}`,pairSelect);o.value=p.pair_id;});show();}; groupSelect.addEventListener('change',selectGroup);pairSelect.addEventListener('change',show);selectGroup();
}).catch(e=>{el('pair-summary').textContent='Analysis summary unavailable: '+e.message;});
})();